name: teneocast_player
description: TeneoCast Player - Cross-platform audio playback application with offline support and remote control (Web, Windows, Android)
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Networking
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11
  
  # Background Tasks (Android)
  workmanager: ^0.5.2
  
  # System Integration (Platform-specific packages added when needed)
  wakelock_plus: ^1.1.4  # Cross-platform
  
  # Caching
  cached_network_image: ^3.3.0
  
  # File System
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  
  # Utilities
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  
  # Environment
  flutter_dotenv: ^5.1.0
  
  # Date/Time
  intl: ^0.18.1
  
  # JSON
  json_annotation: ^4.8.1
  
  # PWA Support (Web) - Built-in Flutter web support

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  
  # Windows Build
  msix: ^3.16.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

# Windows-specific configuration for MSIX packaging
msix:
  config:
    package_name: TeneoCastPlayer
    display_name: TeneoCast Player
    publisher_display_name: TeneoCast
    identity_name: com.teneocast.player
    msix_version: 1.0.0.0
    description: TeneoCast Player - Professional indoor radio playback system
    logo_path: assets/icons/logo.png
    start_up_task: teneocast_player
    capabilities: internetClient, musicLibrary
    
# Platform-specific configurations can be added here
# Android signing, iOS configurations, etc. 