spring:
  application:
    name: player-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/teneocast}
    username: ${SPRING_DATASOURCE_USERNAME:teneocast}
    password: ${SPRING_DATASOURCE_PASSWORD:teneocast_dev}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  security:
    user:
      name: admin
      password: admin123
      roles: USER,ADMIN
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/auth}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.teneocast.player: ${LOG_LEVEL:INFO}
    org.springframework.web.socket: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# WebSocket Configuration
websocket:
  allowed-origins: ${WS_ALLOWED_ORIGINS:http://localhost:3000,https://studio.teneocast.com}
  heartbeat-interval: ${WS_HEARTBEAT_INTERVAL:30000}
  connection-timeout: ${WS_CONNECTION_TIMEOUT:300000}

# Player Configuration
player:
  pairing:
    code-expiry: ${PLAYER_PAIRING_CODE_EXPIRY:300} # 5 minutes in seconds
    code-length: ${PLAYER_PAIRING_CODE_LENGTH:6}
  session:
    timeout: ${PLAYER_SESSION_TIMEOUT:3600} # 1 hour in seconds

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/teneocast
  
  data:
    redis:
      host: redis

logging:
  level:
    com.teneocast.player: INFO
    org.springframework.web.socket: INFO

---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
  
  flyway:
    enabled: false